site_name: 西邮 Linux 兴趣小组培养计划
site_url: https://plan.xiyoulinux.com/
repo_url: https://github.com/xiyou-linuxer/Plan
repo_name: xiyou-linuxer/Plan

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xiyou-linuxer
    - icon: fontawesome/solid/house
      link: https://xiyoulinux.com/

copyright: © 2006-2024 <a href="https://www.xiyoulinux.com/" target="_blank">西邮 Linux 兴趣小组</a><br><a href="https://beian.miit.gov.cn" target="_blank">陕ICP备2023007680号-1</a>

extra_css:
  - asset/custom.css

theme:
  name: material
  icon:
    logo: material/bulletin-board
    repo: fontawesome/brands/github-alt
  favicon: /favicon.ico
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-night
        name: 深色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: light blue
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: 浅色模式
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: orange
      scheme: default
      toggle:
        icon: material/monitor
        name: 系统颜色模式
  language: zh

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
